---
nexus_admin_password: 'admin123' 

nxrm3_privilege_repository:
  - name: "{{ nxrm3_privilege_name }}"  
    description: "{{ nxrm3_privilege_description }}"
    type: "{{ nxrm3_privilege_type }}"
    format: "{{ nxrm3_format }}" 
    content_selector: "{{ nxrm3_privilege_content_selector }}" 
    repository: "{{ nxrm3_repository }}" 
    actions: "{{ nxrm3_actions }}"
       
nxrm3_role:
  - id: "{{ nxrm3_role_id }}"  
    name: "{{ nxrm3_role_name }}"
    description: "{{ nxrm3_role_description }}"
    privileges: "{{ nxrm3_privileges }}"
    roles: "{{ nxrm3_roles }}"

nxrm3_content_selector: 
  - name: "{{ nxrm3_cs_name }}"
    description: 'Create new NXRM3 content selector'
    attributes: 
      - coordinate.groupId =^ "com.mycompany"
  
