---
- name: Calling Groovy script {{ script_name }}
  uri:
    url: "{{ nxrm3_host }}:{{ nxrm3_port }}/service/rest/v1/script/{{ script_name }}/run"
    user: "{{ nxrm3_user }}"
    password: "{{ nxrm3_pwd }}"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    force_basic_auth: yes
    body: "{{ args | to_json }}"
