---
- include: create_role.yml
  with_items: "{{ nxrm3_role }}"
  when: script_name == 'create_role'

- include: create_content_selector.yml
  with_items: "{{ nxrm3_content_selector }}"
  when: script_name == 'create_content_selector'

- include: create_privilege_repository.yml
  with_items: "{{ nxrm3_privilege_repository }}"
  when: script_name == 'create_privilege_repository'

- include: list_metadata.yml
  when: script_name == 'list_roles' or
        script_name == 'list_privileges' or
        script_name == 'list_content_selectors'
  
# - include: create_user.yml
#   with_items: "{{ nexus_local_users }}"

# - include: create_blobstore.yml
#   with_items: "{{ nexus_blobstores }}"
#   when: nexus_restore_point is undefined

# - include: create_repo_maven_proxy.yml
#   with_items: "{{ nexus_repos_maven_proxy }}"

# - include: create_repo_maven_hosted.yml
#   with_items: "{{ nexus_repos_maven_hosted }}"

# - include: create_repo_maven_group.yml
#   with_items: "{{ nexus_repos_maven_group }}"

# - block:
#   - include: create_repo_docker_hosted.yml
#     with_items: "{{ nexus_repos_docker_hosted }}"

#   - include: create_repo_docker_proxy.yml
#     with_items: "{{ nexus_repos_docker_proxy }}"

#   - include: create_repo_docker_group.yml
#     with_items: "{{ nexus_repos_docker_group }}"
#   when: nexus_config_docker

# - block:
#   - include: create_repo_pypi_proxy.yml
#     with_items: "{{ nexus_repos_pypi_proxy }}"

#   - include: create_repo_pypi_hosted.yml
#     with_items: "{{ nexus_repos_pypi_hosted }}"

#   - include: create_repo_pypi_group.yml
#     with_items: "{{ nexus_repos_pypi_group }}"
#   when: nexus_config_pypi

# - block:
#   - include: create_repo_raw_proxy.yml
#     with_items: "{{ nexus_repos_raw_proxy }}"

#   - include: create_repo_raw_hosted.yml
#     with_items: "{{ nexus_repos_raw_hosted }}"

#   - include: create_repo_raw_group.yml
#     with_items: "{{ nexus_repos_raw_group }}"
#   when: nexus_config_raw

# - block:
#   - include: create_repo_rubygems_proxy.yml
#     with_items: "{{ nexus_repos_rubygems_proxy }}"

#   - include: create_repo_rubygems_hosted.yml
#     with_items: "{{ nexus_repos_rubygems_hosted }}"

#   - include: create_repo_rubygems_group.yml
#     with_items: "{{ nexus_repos_rubygems_group }}"
#   when: nexus_config_rubygems

# - block:
#   - include: create_repo_bower_proxy.yml
#     with_items: "{{ nexus_repos_bower_proxy }}"

#   - include: create_repo_bower_hosted.yml
#     with_items: "{{ nexus_repos_bower_hosted }}"

#   - include: create_repo_bower_group.yml
#     with_items: "{{ nexus_repos_bower_group }}"
#   when: nexus_config_bower

# - block:
#   - include: create_repo_npm_proxy.yml
#     with_items: "{{ nexus_repos_npm_proxy }}"

#   - include: create_repo_npm_hosted.yml
#     with_items: "{{ nexus_repos_npm_hosted }}"

#   - include: create_repo_npm_group.yml
#     with_items: "{{ nexus_repos_npm_group }}"
#   when: nexus_config_npm

# - include: create_repo_gitlfs_hosted.yml
#   with_items: "{{ nexus_repos_gitlfs_hosted }}"
#   when: nexus_config_gitlfs

# - include: create_task.yml
#   with_items: "{{ nexus_scheduled_tasks }}"

