- hosts: localhost
  vars:
    image_name: howdy
    version: 1.2
  tasks:
    - name: Push image to local registry
      docker_image:
        name: "{{ image_name }}"
        repository: "{{ item.registry }}"
        tag: "{{ version }}"
      with_items:
        - { registry: 'sola.local:18082' }
      register: op

    - debug:
        var: op

