- hosts: localhost
  vars:
    image_name: howdy
    version: 1.2
  tasks:
    - name: Push image to local registry
      shell: /usr/local/bin/docker push "{{ item }}/{{ image_name }}:{{ version }}"
      with_items: "{{ docker_registries }}"
      register: op

    - debug:
        var: op

