- hosts: localhost
  vars:
    image_name: hello-world
    version: 5.5
  tasks:
    - name: Buuld and tag docker image
      shell: chdir=/Users/sotudeko/Development/docker-image-scan/hello-world-server /usr/local/bin/docker build -t "{{ item }}/{{ image_name }}:{{ version }}" .
      with_items: "{{ docker_registries }}"
      register: op

    - debug:
        var: op

    - name: Push image to local registry
      shell: chdir=/Users/sotudeko/Development/docker-image-scan/hello-world-server /usr/local/bin/docker push "{{ item }}/{{ image_name }}:{{ version }}"
      with_items: "{{ docker_registries }}"
      register: op

    - debug:
        var: op

