- hosts: nxrm3_controller
  vars:
    username: admin
    passwd: admin123
    host: http://localhost
    port: 8082
    repository: mvn-releases
  tasks:
    - name: Upload maven component to Nexus Repository "{{ repository }}"
      command: curl -v -u "{{ username }}":"{{ passwd }}" \
             -X POST "{{ host }}:{{ port }}/service/rest/v1/components?repository={{ repository }}" \
             -F maven2.groupId="{{ group }}" \
             -F maven2.artifactId="{{ artifact }}" \
             -F maven2.version="{{ version }}" \
             -F maven2.asset1=@"{{ artifact_path }}" \
             -F maven2.asset1.extension="{{ extension }}" \
             -F maven2.generate-pom=true
      args:
        warn: false
