- hosts: nxrm3_controller
  tasks:
    - name: Upload component to Nexus Repository "{{ repository }}"
      shell: curl -v -u "{{ item.user }}":"{{ item.passwd }}" \
             -X POST "{{ item.host }}:{{ item.port }}/service/rest/v1/components?repository={{ repository }}" \
             -F maven2.groupId="{{ group }}" \
             -F maven2.artifactId="{{ artifact }}" \
             -F maven2.version="{{ version }}" \
             -F maven2.asset1=@"{{ artifact_path }}" \
             -F maven2.asset1.extension="{{ extension }}" \
             -F maven2.generate-pom=true
      args:
        warn: false
      loop: "{{ nxrm3_instances }}"
